# Generated by Django 3.2.5 on 2021-11-04 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='status',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='csvfile',
            name='upload_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
