# Generated by Django 3.2.5 on 2021-11-09 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms_dashboard', '0003_auto_20211108_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csvfile',
            name='csv_file',
            field=models.FileField(max_length=999, upload_to='csv_files'),
        ),
    ]
