# Generated by Django 3.2.5 on 2021-11-10 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms_dashboard', '0003_alter_csvfile_csv_file'),
        ('cms_dashboard', '0004_alter_csvfile_csv_file'),
    ]

    operations = [
    ]
