# Generated by Django 3.2.5 on 2021-11-04 14:04

from django.db import migrations, models
import student_parents.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonform',
            name='aadhar_no',
            field=models.CharField(default='0', max_length=12, validators=[student_parents.models.CommonForm.validate_digit_length]),
        ),
    ]
