# Generated by Django 3.2.5 on 2021-11-05 08:56

from django.db import migrations, models
import student_parents.models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parents', '0002_alter_commonform_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonform',
            name='aadhar_no',
            field=models.CharField(max_length=12, validators=[student_parents.models.CommonForm.validate_digit_length]),
        ),
    ]
