# Generated by Django 3.2.5 on 2021-11-10 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_parents', '0003_alter_commonform_aadhar_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='child',
            name='class_standard',
            field=models.CharField(choices=[('UKG', 'UKG'), ('LKG', 'LKG'), ('PLG', 'Play Group'), ('NRS', 'Narsery'), ('1', 'Class 1'), ('2', 'Class 2'), ('3', 'Class 3'), ('4', 'Class 4'), ('5', 'Class 5'), ('6', 'Class 6'), ('7', 'Class 7'), ('8', 'Class 8'), ('9', 'Class 9'), ('10', 'Class 10'), ('11', 'Class 11'), ('12', 'Class 12')], max_length=50),
        ),
    ]
