# Generated by Django 3.2.5 on 2021-09-15 10:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=500)),
                ('school_image', models.CharField(max_length=999)),
                ('address', models.TextField(max_length=250)),
                ('board', models.CharField(choices=[('SB', 'STATE BOARD'), ('CBSE', 'CBSE'), ('ICSE', 'ICSE'), ('CISCE', 'CISCE'), ('NIOS', 'NIOS'), ('IB', 'IB'), ('CIE', 'CIE')], default='SB', max_length=5)),
                ('co_ed_status', models.CharField(choices=[(1, 'Co-Education'), (2, 'Girlsonly'), (3, 'Boysonly')], max_length=10)),
                ('ownership', models.CharField(choices=[('UN', 'UNKNOWN'), ('PR', 'PRIVATE'), ('PRA', 'PRIVATE-AIDED')], default='UN', max_length=3)),
                ('sf_ratio', models.CharField(max_length=6)),
                ('class_offered', models.CharField(choices=[(1, 'Nursery - Class 12'), (2, 'Nursery - Class 10'), (3, 'Toddler - Class 12'), (4, 'Pre-Nursery - Class 5'), (5, 'Pre-Nursery - Class 8'), (6, 'Nursery - Class 8'), (7, 'Class 1 - Class 12'), (8, 'Pre-Nursery - Class 12'), (9, 'Pre-Nursery - KG'), (10, 'Nursery - UKG'), (11, 'Pre-Nursery - Class 10'), (12, 'Class 6 - Class 12'), (13, 'Class 1 - Class 8'), (14, 'Pre-Nursery - UKG'), (15, 'Nursery - KG'), (16, 'Pre-School (Nursery), - Class 12'), (17, 'LKG - Class 12'), (18, 'Nursery - Class 3'), (19, 'Pre-Nursery - Class 7'), (20, 'Play Group - Class 1'), (21, 'Nursery - Class 11'), (22, 'Nursery - Class 7'), (23, 'Nursery - Class 9'), (24, 'Pre-School (Nursery), - Class 5'), (25, 'LKG - Class 10'), (26, 'Pre-School (Nursery), - Class 10'), (27, 'Pre-Nursery - Class 2'), (28, 'Pre-Nursery - Prep'), (29, 'KG - Class 12'), (30, 'Pre-School (Nursery), - Class 1'), (31, 'Nursery - Class 5'), (32, 'LKG - Class 9'), (33, 'Nursery - Class 2'), (34, 'UKG - Class 12'), (35, 'Class 1 - Class 11'), (36, 'Play Way - Class 12'), (37, 'Pre-School (Nursery), - Pre-Primary (KG),'), (38, 'Play Group - UKG'), (39, 'Pre-Nursery - Class 6'), (40, 'UKG - Class 4'), (41, 'KG - Class 10'), (42, 'Play Way - Class 10'), (43, 'KG - Class 8'), (44, 'Play School - Class 8'), (45, 'Class 1 - Class 5'), (46, 'Pre-Nursery - Class 9'), (47, 'Class 6 - Class 10'), (48, 'Play Group - Class 5'), (49, 'Nursery - Class 1'), (50, 'Nursery - Class 6'), (51, 'Pre-Nursery - Class 3'), (52, 'Class 3 - Class 12'), (53, 'Class 1 - Class 10'), (54, 'Class 6 - Class 8'), (55, 'UKG - Class 10'), (56, 'Class 1 - Class 6'), (57, 'LKG - Class 8'), (58, 'Pre-Nursery - Nursery'), (59, 'UKG - Class 5'), (60, 'Class 1 - Class 7'), (61, 'LKG - Class 5'), (62, 'Class 9 - Class 12'), (63, 'Play Group - Class 8'), (64, 'Play Group - Class 10'), (65, 'UKG - Class 8')], max_length=100)),
                ('verified', models.BooleanField(default=False)),
                ('owner', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=500)),
                ('webiste', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('year_of_establishment', models.CharField(max_length=500)),
                ('campus_size', models.CharField(max_length=500)),
                ('campus_type', models.CharField(max_length=500)),
                ('class_type', models.CharField(max_length=500)),
                ('boarding', models.CharField(max_length=500)),
                ('hall_of_fame', models.CharField(max_length=99999)),
                ('gallery', models.CharField(max_length=99999)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=999)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_reviews', to='schools.schooldetail')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'School Reviews',
            },
        ),
        migrations.CreateModel(
            name='SchoolRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=14)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee_name', models.CharField(max_length=50)),
                ('fee_amount', models.IntegerField()),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_refer', to='schools.school')),
            ],
        ),
        migrations.CreateModel(
            name='SchoolFacilities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ac_classes', models.BooleanField(default=False)),
                ('smart_classes', models.BooleanField(default=False)),
                ('wifi', models.BooleanField(default=False)),
                ('boys_hostel', models.BooleanField(default=False)),
                ('girls_hostel', models.BooleanField(default=False)),
                ('auditorium_media_room', models.BooleanField(default=False)),
                ('cafeteria_canteen', models.BooleanField(default=False)),
                ('library_reading_room', models.BooleanField(default=False)),
                ('playground', models.BooleanField(default=False)),
                ('cctv', models.BooleanField(default=False)),
                ('gps_bus_tracking_app', models.BooleanField(default=False)),
                ('student_tracking_app', models.BooleanField(default=False)),
                ('alumni_association', models.BooleanField(default=False)),
                ('day_care', models.BooleanField(default=False)),
                ('meals', models.BooleanField(default=False)),
                ('medical_room', models.BooleanField(default=False)),
                ('transportation', models.BooleanField(default=False)),
                ('art_and_craft', models.BooleanField(default=False)),
                ('dance', models.BooleanField(default=False)),
                ('debate', models.BooleanField(default=False)),
                ('drama', models.BooleanField(default=False)),
                ('gardening', models.BooleanField(default=False)),
                ('music', models.BooleanField(default=False)),
                ('picnics_and_excursion', models.BooleanField(default=False)),
                ('skating', models.BooleanField(default=False)),
                ('horse_riding', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
                ('indoor_sports', models.BooleanField(default=False)),
                ('outdoor_sports', models.BooleanField(default=False)),
                ('swimming_pool', models.BooleanField(default=False)),
                ('karate', models.BooleanField(default=False)),
                ('taekwondo', models.BooleanField(default=False)),
                ('yoga', models.BooleanField(default=False)),
                ('computer_lab', models.BooleanField(default=False)),
                ('science_lab', models.BooleanField(default=False)),
                ('robotics_lab', models.BooleanField(default=False)),
                ('ramps', models.BooleanField(default=False)),
                ('washrooms', models.BooleanField(default=False)),
                ('elevators', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
            options={
                'verbose_name_plural': 'Facilities',
            },
        ),
    ]
