# Generated by Django 3.2.5 on 2021-09-15 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_auto_20210915_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='co_ed_status',
            field=models.CharField(choices=[('Co-Education', 'Co-Education'), ('Girlsonly', 'Girlsonly'), ('Boysonly', 'Boysonly')], max_length=100),
        ),
    ]
