# Generated by Django 3.2.5 on 2021-09-15 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0003_alter_school_co_ed_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetail',
            name='hall_of_fame',
        ),
        migrations.CreateModel(
            name='HallofFame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
