# Generated by Django 3.2.5 on 2021-09-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_auto_20210915_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_image',
            field=models.CharField(blank=True, max_length=999),
        ),
    ]
