# Generated by Django 3.2.5 on 2021-09-21 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_school_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schooldetail',
            name='boarding',
        ),
        migrations.RemoveField(
            model_name='schooldetail',
            name='class_type',
        ),
    ]
