# Generated by Django 3.2.5 on 2021-09-24 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_schoolgallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolfee',
            name='class_type',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
