# Generated by Django 3.2.5 on 2021-09-24 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0008_schoolfee_class_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schoolfee',
            old_name='class_type',
            new_name='standard',
        ),
    ]
